feat: hug the codec
Snownee/Lychee pull request #70
Opened 2024-02-04 04:31 UTC by SettingDust

2024-02-04 08:18 UTC, Snownee requested changes

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +						}).orElse(1).forGetter(AnvilCraftingRecipe::levelCost),
`ExtraCodecs.validate`

2024-02-04 08:18 UTC, Snownee commented on gradle.properties
> +kiwi_version=13.0.0
Kiwi该更新了。另外1.20.4+将强制依赖Kiwi

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/context/recipes/AnvilContext.java
> +	private final Pair<ItemStack, ItemStack> input;
应该是ItemContext的一部分，不明白为什么放在这里

2024-02-04 08:18 UTC, Snownee commented on src/main/resources/assets/lychee/lang/en_us.json
> +  "result.lychee.default": "§7- ",
修改键名时请将其他语言一并修改

2024-02-04 08:18 UTC, Snownee commented on src/main/resources/lychee.mixins.json
> +        "LocationPredicate$PositionPredicateAccessor",
使用Access作为结尾。明明尽量简短

2024-02-04 08:18 UTC, Snownee commented on src/main/resources/lychee.mixins.json
> +        "predicates.LocationPredicate$PositionPredicateAccessor",
使用Access作为结尾。明明尽量简短

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/anvil_crafting/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe implements LycheeRecipe<AnvilContext>, Comparable<AnvilCraftingRecipe> {
原先通过继承改写的匹配逻辑如今要怎么实现？（EverPotion）

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
原先通过继承改写的匹配逻辑如今要怎么实现？（EverPotion）

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeType.java
> +	private Supplier<Boolean> isEmpty = Suppliers.memoize(() -> recipes.isEmpty());
为什么要懒加载？应改名empty或emptyState

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +public class LycheeContext extends HashMap<LycheeContextType<?>, LycheeContextValue<?>> implements DummyContainer {
继承HashMap的必要性？而不是作为成员？在我看来，只需要get和put方法。如必要，为什么不用IdentityHashMap

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
序列化是必要且可行的吗？ItemStackHolderCollection有瞬时性，世界中的ItemStackHolderCollection会随时变动/失效。我看不出把context分为不同组件的必要性。

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/predicates/BlockPredicate.java
> +package snownee.lychee.util.predicates;
从原版复制出来的原因？如有请注明

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +				 .forGetter(LycheeRecipe::postActions);
1. 丧失了将JsonObject解析为单个元素的List的能力
2. 应使用`orElseGet`

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/action/PostActionType.java
> +					.orElse(new ContextualCommonHolder())
应使用`orElseGet`

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
为什么变成`split`了？

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +			Codec.BOOL.fieldOf("hide_in_viewer").orElse(false).forGetter(LycheeRecipe::hideInRecipeViewer);
`optionalFieldOf`？下面还有几个类似问题

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +								   .orElse(MinMaxBounds.Ints.ANY)
不同配方类型，范围应该是不同的

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeCommonHolder.java
> +		Optional<String> comment,
应该使用`@Nullable String`

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/contextual/ConditionHolder.java
> +									  .forGetter(ConditionHolder::secret),
把你的缩进改改吧，好丑

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/contextual/ContextualConditionDisplay.java
> +	LoadingCache<ContextualConditionType<?>, String> DESCRIPTION_ID_CACHE =
此处缓存的必要较小，并且你没有考虑用户切换语言的情况

2024-02-04 08:18 UTC, Snownee commented on src/main/java/snownee/lychee/util/contextual/ContextualImpl.java
> +							.orElse(new ContextualCommonHolder())
orElseGet

2024-02-04 08:59 UTC, SettingDust commented on src/main/java/snownee/lychee/context/recipes/AnvilContext.java
> +	private final Pair<ItemStack, ItemStack> input;
https://github.com/Snownee/Lychee/blob/1.20-fabric/src/main/java/snownee/lychee/anvil_crafting/AnvilContext.java#L13-L14

因为他俩在这里

2024-02-04 09:01 UTC, SettingDust commented on src/main/java/snownee/lychee/recipes/anvil_crafting/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe implements LycheeRecipe<AnvilContext>, Comparable<AnvilCraftingRecipe> {
没理解XD

2024-02-04 09:01 UTC, SettingDust commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
没理解XD

2024-02-04 09:04 UTC, SettingDust commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeType.java
> +	private Supplier<Boolean> isEmpty = Suppliers.memoize(() -> recipes.isEmpty());
没什么实际理由，因为原先那里就是刷新时全部加载一遍，我感觉没必要，就这样了

2024-02-04 09:05 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +public class LycheeContext extends HashMap<LycheeContextType<?>, LycheeContextValue<?>> implements DummyContainer {
没有必要

2024-02-04 09:07 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
这样做的目的是需要存储到 marker 的数据不需要特别对待，只要实现接口会自动在 maker 里存储，而不是之前写特有逻辑

ItemContext 就没有实现序列化的接口，也就不会被存储

2024-02-04 09:24 UTC, SettingDust commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
`shrink` 是减少当前 ItemStack 的数量，`split` 也一样减少了，只是会返回被拿走的物品，可以拿到实际消耗的数量

2024-02-04 09:26 UTC, SettingDust commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +								   .orElse(MinMaxBounds.Ints.ANY)
这里和 https://github.com/Snownee/Lychee/blob/1.20-fabric/src/main/java/snownee/lychee/core/recipe/LycheeRecipe.java#L205-L208 是一个作用，作为默认值，之后会根据每个配方的实际序列化情况选择 Codec

2024-02-04 09:31 UTC, SettingDust commented on src/main/java/snownee/lychee/util/contextual/ContextualConditionDisplay.java
> +	LoadingCache<ContextualConditionType<?>, String> DESCRIPTION_ID_CACHE =
嗯

2024-02-04 09:33 UTC, SettingDust commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeCommonHolder.java
> +		Optional<String> comment,
我是因为 record 会生成访问方法，没办法单独写个 getter 来返回 Optional，这里为什么需要 nullable string?

2024-02-04 09:51 UTC, SettingDust commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +			Codec.BOOL.fieldOf("hide_in_viewer").orElse(false).forGetter(LycheeRecipe::hideInRecipeViewer);
这里为什么需要 `optionalFieldOf`，没理解，它的类型也不是 `Optional`

2024-02-04 14:33 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +public class LycheeContext extends HashMap<LycheeContextType<?>, LycheeContextValue<?>> implements DummyContainer {
速度更快

2024-02-04 14:34 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
看这个实现：https://github.com/Snownee/EverPotion/blob/1.19.2-fabric/src/main/java/snownee/everpotion/crafting/FallbackCoreRecipe.java

2024-02-04 14:39 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeType.java
> +	private Supplier<Boolean> isEmpty = Suppliers.memoize(() -> recipes.isEmpty());
但之前必定已经执行过`refreshCache`，所有配方已经完全加载了

2024-02-04 14:52 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeCommonHolder.java
> +		Optional<String> comment,
1. `optionalFieldOf`有直接提供默认值的方法
2. https://stackoverflow.com/questions/31922866/why-should-java-8s-optional-not-be-used-in-arguments

2024-02-04 14:53 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeCommonHolder.java
> +		Optional<String> comment,
已修改代码

2024-02-04 14:55 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +			Codec.BOOL.fieldOf("hide_in_viewer").orElse(false).forGetter(LycheeRecipe::hideInRecipeViewer);
使用`.optionalFieldOf("hide_in_viewer", false)`更直观，且序列化回来时可以更加简短

2024-02-04 15:02 UTC, Snownee commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
`ItemStackHolder.split`和`ItemStackHolderCollection.split`行为不同，应该起不同的名字

2024-02-04 15:04 UTC, Snownee commented on src/main/java/snownee/lychee/util/predicates/BlockPredicate.java
> +package snownee.lychee.util.predicates;
我认为理由不足，应该将增加的代码放入`BlockPredicateExtensions`

2024-02-04 15:12 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
问题是你说的实现序列化接口的Type在每种配方类型里都是必要的

2024-02-04 15:58 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
> 问题是你说的实现序列化接口的Type在每种配方类型里都是必要的

不是的

2024-02-04 16:04 UTC, SettingDust commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
手写？

2024-02-04 16:16 UTC, SettingDust commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
> `ItemStackHolder.split`和`ItemStackHolderCollection.split`行为不同，应该起不同的名字

我觉得 `ItemStackHolder.split` 和 `ItemStackHolderCollection.split` 是一个逻辑，都是减去数量之后返回分割出的 ItemStack，没明白命名需要怎么区分

2024-02-04 16:21 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
显然不行。另外`RecordCodecBuilder`并不是只能接受record

2024-02-04 16:22 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
请举出反例

2024-02-04 16:25 UTC, Snownee commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
`ItemStackHolderCollection.split`并不会减少`ItemStackHolderCollection`中总共的物品数量。`ItemStackHolder.split`应改为`shrink`

2024-02-04 16:32 UTC, SettingDust commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
> 显然不行。

那我倾向于这个上下文使用一个 `AnvilContext`，而不是继承

> 另外`RecordCodecBuilder`并不是只能接受record

知道的

2024-02-04 16:34 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
> 请举出反例

除了 JsonContext 和 ActionContext 之外的 Context Type 都没有序列化的部分

2024-02-04 16:36 UTC, SettingDust commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
> `ItemStackHolderCollection.split`并不会减少`ItemStackHolderCollection`中总共的物品数量。`ItemStackHolder.split`应改为`shrink`

你的意思是 `stacksNeedHandle` 也包含在里面所以不减少总共的物品数量吗？
我是觉得放到待处理区域已经和其他的不是一个状态了，也不属于任一 Holder 了

2024-02-04 17:03 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
但是有哪个LycheeContext是不需要ActionContext的？

2024-02-04 19:55 UTC, Snownee commented on src/main/java/snownee/lychee/util/input/ItemStackHolderCollection.java
> +			holder.split(times);
但语义是不同的

2024-02-05 06:21 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
> 但是有哪个LycheeContext是不需要ActionContext的？

没理解，有必要的 Context 也有不一定存在的 Context

2024-02-05 06:23 UTC, SettingDust commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +public record AnvilCraftingRecipe(
啊，看错了，昨天看成 Context 了，那就转换成 class 呗

2024-02-05 18:23 UTC, Snownee requested changes

2024-02-05 18:23 UTC, Snownee commented on src/main/java/snownee/lychee/recipes/AnvilCraftingRecipe.java
> +	}
什么情况需要用到这个？

2024-02-05 18:23 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeType.java
> +	private Supplier<Boolean> isEmpty = Suppliers.memoize(() -> recipes.isEmpty());
仍未改名

2024-02-05 18:23 UTC, Snownee commented on src/main/java/snownee/lychee/util/recipe/LycheeRecipeSerializer.java
> +								   .orElse(MinMaxBounds.Ints.ANY)
> 之后会根据每个配方的实际序列化情况选择 Codec

应等待相关功能实现后再标记为“已解决”

2024-02-05 18:23 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +	}
潜在的NPE

2024-02-05 18:23 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
每个LycheeContext都有Level，都有Random，都有Loot Params，那你多加一步Map#get的目的是什么呢？每次创建LycheeContext时都要初始化一个HashMap，也是不小的开销

2024-02-06 02:28 UTC, SettingDust reviewed
我觉得在这里考虑 RAM 有些过早优化了，我不认为这两种结构能造成多大的差异

2024-02-06 02:48 UTC, Snownee commented
> 我觉得在这里考虑 RAM 有些过早优化了，我不认为这两种结构能造成多大的差异

倒不如说为什么要把原来的写法改了。Lychee是一个有两年历史的项目。

2024-02-06 03:05 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
不总是都有，比如 Codec 反序列化回来的时候就没有，需要调用点之后再填入这些上下文
至于开销，我不认为会造成可见的 CPU 时间占用，如果有性能问题再优化

2024-02-06 03:17 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
1. 把LycheeContext反序列化回来的目的是执行Action，执行Action是一定需要Level, Random的
2. Lychee配方匹配是相当性能敏感的，用户可能每秒都在查询配方，一次爆炸/随机刻tick里面，如果有相应配方，被炸毁/tick的每一个方块都要创建一个新的LycheeContext，希望你能意识到这一点

2024-02-06 03:37 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
1. 是一定需要，但是反序列化之后，在调用点填入之前，这个上下文确实是缺失的
2. Sponge 的上下文是类似结构，https://github.com/SpongePowered/Sponge/blob/api-10/src/main/java/org/spongepowered/common/event/tracking/SpongeCauseStackFrame.java#L42-L43，且应用场景类似（事件上下文），但是引入了对象池 https://github.com/SpongePowered/Sponge/blob/api-10/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L208-L210，所以如果有性能问题，那我会使用对象池

2024-02-06 03:47 UTC, Snownee commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
不只如此，每一次调用get()都是额外消耗。算了，之后我自己改吧

2024-02-06 03:54 UTC, SettingDust commented on src/main/java/snownee/lychee/util/context/LycheeContext.java
> +			}, Function.identity());
> 不只如此，每一次调用get()都是额外消耗。算了，之后我自己改吧

这对性能的影响有多大尚未可知吧？但是这样的结构比起纯继承 + builder 耦合度更低，也更易扩展，

2024-02-07 03:56 UTC, SettingDust commented on src/main/java/snownee/lychee/util/codec/BlockPredicateCodec.java
> +				//TODO how to handle ANY?
Codec 返回个 Optional？

2024-02-07 04:10 UTC, Snownee commented on src/main/java/snownee/lychee/util/codec/BlockPredicateCodec.java
> +				//TODO how to handle ANY?
等项目能运行起来之后再解决

2024-02-28 11:36 UTC, Snownee commented on src/main/java/snownee/lychee/util/predicates/BlockPredicateExtensions.java
> +	public static boolean matches(Level level, BlockPredicate predicate, LycheeContext context) {
为什么不从LycheeContext里获取？

2024-02-28 11:38 UTC, Snownee commented on src/main/java/snownee/lychee/mixin/recipes/dripstone/BlockStateMixin.java
> +public class BlockStateMixin {
如果DF lib还更新的话，可以在MixinPlugin里选择性加载

2024-02-28 11:43 UTC, SettingDust commented on src/main/java/snownee/lychee/util/predicates/BlockPredicateExtensions.java
> +	public static boolean matches(Level level, BlockPredicate predicate, LycheeContext context) {
不知道 Recipe#matches 传入的 Level 和 context 里的是不是一致

2024-02-29 05:36 UTC, Snownee commented on src/main/resources/lychee.mixins.json
为什么缩进改了？

2024-04-04 19:10 UTC, Snownee approved these changes

2024-04-04 19:11 UTC, Snownee commented
moved the discussion to discord

2024-04-09 07:30 UTC, Snownee requested changes

2024-04-09 07:30 UTC, Snownee commented on src/main/java/snownee/lychee/action/PlaceBlock.java
> +		return block == null ? List.of() : List.of(block);
block应该是非空的

2024-04-09 07:30 UTC, Snownee commented on src/main/java/snownee/lychee/compat/rei/category/BlockCrushingRecipeCategory.java
> +			var anyLandingBlock = recipe.landingBlock() == BlockPredicateExtensions.ANY;
应该用BlockPredicateExtensions.isAny()

2024-04-18 02:25 UTC, merged