feat: port JEI to 1.21
Snownee/Lychee pull request #87
Opened 2024-07-04 03:38 UTC by SettingDust

2024-07-11 19:29 UTC, Snownee commented
![image](https://github.com/Snownee/Lychee/assets/16059084/c50f2e54-2ff2-4838-bf1a-69c2521a907e)
hmmm 我不觉得这是正常的。另外所有物品x和y轴都有1像素的位移。

2024-07-14 06:32 UTC, KasumiNova commented
草

2024-07-15 04:21 UTC, SettingDust commented
@Snownee done. 最好 review 下，不然没法再次请求 review xd

2024-07-15 05:02 UTC, Snownee commented
> @Snownee done. 最好 review 下，不然没法再次请求 review xd

我也不知道你完全不调试的，我都要怀疑是我自己的问题了

2024-07-15 05:06 UTC, Snownee commented
![image](https://github.com/user-attachments/assets/3b50ad6a-3b7a-4949-83cc-7e11b9bc55aa)
![image](https://github.com/user-attachments/assets/aa8ff473-184c-45d6-8c3a-4703599ced1a)

没什么大问题了，还是有一些错位问题，以及似乎所有配方都高出来一截

2024-07-15 05:06 UTC, Snownee commented
![image](https://github.com/user-attachments/assets/0b83673b-6a5f-4ec2-9cbc-fb118174220c)

这个配方不见了

2024-07-15 05:07 UTC, Snownee requested changes
见评论

2024-07-15 05:12 UTC, SettingDust commented
> > @Snownee done. 最好 review 下，不然没法再次请求 review xd
> 
> 我也不知道你完全不调试的，我都要怀疑是我自己的问题了

我以为我调试了，结果我看的是 REI 的不是 JEI 的=。=

2024-07-15 12:31 UTC, merged